name: Compile&Publish

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - run: |
          cd src
          npm install --force
          npm run build
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.event_name != 'pull_request'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: github.event_name != 'pull_request'
      
      - name: Build and push atomci frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/Dockerfile
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/kubelilin-dashboard:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kubelilin-dashboard:latest
        if: github.event_name != 'pull_request'
        
        
        
